theme: midnight
title: Alinta Wang
author: alintawang
email: alinta.wang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Master's student at the University of Texas at Dallas studying Computer Science with a focus in Cybersecurity.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
