theme: minima
title: Alinta Wang
author: alintawang
email: alinta.wang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Master's student at the University of Texas at Dallas studying Computer Science with a focus in Cybersecurity.

# social links
instagram_username: alinta
github_username:  http

show_excerpts: true # set to false to remove excerpts on the homepage
